apiVersion: security.meslami.io/v1alpha1
kind: SecurityPolicyProfile
metadata:
  name: {{ .Values.securityProfile.name }}
  namespace: {{ .Values.operator.namespace }}
spec:
  severityThreshold: {{ .Values.securityProfile.severityThreshold }}

  rules:
    requirePodSecurityRestricted: true

    forbidPrivilegedContainers: true
    forbidHostNetwork: true
    forbidHostPID: true
    forbidHostPath: true
    requireRunAsNonRoot: true
    forbidLatestImageTag: true
    flagDefaultServiceAccount: true

    requireReadinessProbe: true
    requireLivenessProbe: false
    requireResourceRequests: true
    requireResourceLimits: true

    requireDeploymentReplicas: true
    minimumDeploymentReplicas: 2
    requireRollingUpdateStrategy: true

    requireNetworkPolicy: true
    requireCiliumNetworkPolicy: false

    forbidClusterAdminRoleBinding: true
    forbidWildcardRBAC: true
    flagDefaultServiceAccountRBAC: true
