apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.operator.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: operator
          image: {{ .Values.operator.image }}
          imagePullPolicy: {{ .Values.operator.imagePullPolicy }}
          command:
            - kopf
            - run
            - /app/app/operator.py
            - --verbose
          env:
            - name: WATCH_NAMESPACES
              value: "{{ .Values.operator.watchNamespaces }}"
            - name: EXCLUDE_NAMESPACES
              value: "{{ .Values.operator.excludeNamespaces }}"
            - name: DIRTY_EVENT_THRESHOLD
              value: "{{ .Values.operator.dirtyEventThreshold }}"
            - name: DIRTY_FLUSH_SECONDS
              value: "{{ .Values.operator.dirtyFlushSeconds }}"
            - name: DIRTY_WORKER_INTERVAL_SECONDS
              value: "{{ .Values.operator.dirtyWorkerIntervalSeconds }}"
            - name: FULL_RESYNC_SECONDS
              value: "{{ .Values.operator.fullResyncSeconds }}"
