apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.operator.namespace }}
  labels:
    app.kubernetes.io/name: namespace-security-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
