apiVersion: security.meslami.io/v1alpha1
kind: SecurityPolicyProfile
metadata:
  name: default-profile
  namespace: security-operator-demo
spec:
  severityThreshold: medium
  rules:
    requirePodSecurityRestricted: true
    forbidPrivilegedContainers: true
    forbidHostNetwork: true
    forbidHostPID: true
    forbidHostPath: true
    requireRunAsNonRoot: true
    forbidLatestImageTag: true
    flagDefaultServiceAccount: true
    requireReadinessProbe: true
    requireResourceRequests: true
    requireResourceLimits: true
    requireNetworkPolicy: true
    flagLoadBalancerServices: true
    flagNodePortServices: true
    flagSensitiveExposedPorts: true
    requireIngressTLS: true
